import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { execSync } from "node:child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const qaProduct = (process.argv[2] === "qa-product");

// Build provenance for src/buildInfo.ts. manifest.json keeps upstream's
// version, so the commit and build time are how one fork build is told
// from another in the settings tab.
function git(args) {
	try {
		return execSync(`git ${args}`, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
	} catch {
		return "";
	}
}
const buildInfo = JSON.stringify({
	commit: git("rev-parse --short HEAD") || "unknown",
	branch: git("rev-parse --abbrev-ref HEAD") || "unknown",
	builtAt: new Date().toISOString(),
});
// define takes a JS expression; a JSON string literal of the JSON object.
const buildInfoDefine = JSON.stringify(buildInfo);

const sharedConfig = {
	banner: { js: banner },
	bundle: true,
	external: [
		"obsidian",
		"electron",
		// Obsidian ships these CM6 packages at runtime.
		// We MUST externalize them to avoid version mismatches.
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: (prod || qaProduct) ? false : "inline",
	treeShaking: true,
	minify: (prod || qaProduct),
};

// ---------------------------------------------------------------------------
// QA product build — NOT a release artifact.
//
// Built with __YAOS_QA_HARNESS_ENABLED__=true so esbuild keeps the Engine
// control port code. Used for Puppeteer/Obsidian scenario runs only.
// Output: qa/obsidian-harness/product-main.js
//
// Usage:
//   node esbuild.config.mjs qa-product        # one-shot QA product build
//   npm run build:qa-product                   # tsc typecheck + QA product build
// ---------------------------------------------------------------------------
if (qaProduct) {
	const qaProductContext = await esbuild.context({
		...sharedConfig,
		entryPoints: ["src/main.ts"],
		outfile: "qa/obsidian-harness/product-main.js",
		define: {
			// true → esbuild KEEPS the EngineControlPort block for harness use
			"__YAOS_QA_HARNESS_ENABLED__": "true",
			"__OG_CLOUD_BUILD__": buildInfoDefine,
		},
	});
	await qaProductContext.rebuild();
	process.exit(0);
}

// ---------------------------------------------------------------------------
// Product bundle — the only shipped artifact. Contains the sync engine and the
// debug/Observer runtime (src/telemetry/), which is reachable only when
// settings.debug is on. Must not contain Engine control capabilities:
// __YAOS_QA_HARNESS_ENABLED__=false → esbuild dead-code-eliminates the port.
// ---------------------------------------------------------------------------
const mainContext = await esbuild.context({
	...sharedConfig,
	entryPoints: ["src/main.ts"],
	outfile: "main.js",
	define: {
		// false → esbuild eliminates getEngineControlPort, ingestDiskFileNow, etc.
		"__YAOS_QA_HARNESS_ENABLED__": "false",
		"__OG_CLOUD_BUILD__": buildInfoDefine,
	},
});

if (prod) {
	await mainContext.rebuild();
	process.exit(0);
} else {
	await mainContext.watch();
}
