// Provenance (2026-09-24): the update manifest must describe THIS fork.
//
// UPDATE_MANIFEST_URLS still pointed at kavinsood/yaos, so the plugin read a
// third party's release metadata and reported it as its own. The settings
// tab's "Latest plugin" and "Latest server" rows showed upstream's numbers,
// and worse, getHardCompatibilityBlockReason() feeds on
// minCompatibleServerVersionForPlugin and latestPluginVersion from that same
// manifest and calls stopSyncRuntimeForCompatibility() — so an upstream
// release could have halted sync on a vault upstream knows nothing about.
//
// The fork publishes its own update-manifest.json on each plugin release
// (build.sh release), generated by build-server-release.mjs from
// server/src/version.ts. There is deliberately no upstream fallback in the
// URL list: a missing manifest leaves the rows "Unknown" and every guard
// inert, which is the correct failure, whereas a fallback would quietly
// restore exactly the behaviour this removes.

import { readSource, suite } from "../harness.ts";

const s = suite("update-manifest-source");

const FORK = "mrilikecoding/og-cloud";
const UPSTREAM = "kavinsood/yaos";

const capabilitySource = readSource("src/runtime/capabilityUpdateService.ts");
const releaseScriptSource = readSource("build-server-release.mjs");

/** The UPDATE_MANIFEST_URLS array literal, so assertions ignore the rest of the file. */
function updateManifestUrlsBlock(source: string): string {
	const match = /const UPDATE_MANIFEST_URLS = \[([\s\S]*?)\] as const;/.exec(source);
	return match?.[1] ?? "";
}

s.section("Test 1: the plugin fetches the fork's update manifest, with no upstream fallback");
{
	const block = updateManifestUrlsBlock(capabilitySource);
	s.check(block !== "", "UPDATE_MANIFEST_URLS is still declared as a const array");
	s.check(block.includes(FORK), "the URL list names the fork");
	s.check(!block.includes(UPSTREAM), "the URL list does not fall back to upstream");
	const urls = [...block.matchAll(/"([^"]+)"/g)].map((m) => m[1]!);
	s.check(urls.length === 1, `exactly one source configured (found ${urls.length})`);
	s.check(
		urls[0] === `https://github.com/${FORK}/releases/latest/download/update-manifest.json`,
		"it is the fork's latest-release asset URL",
	);
}

s.section("Test 2: the generated manifest's own links point at the fork");
{
	// The emitted values are asserted end-to-end in
	// tests/contracts/release-compatibility-matrix.ts, which runs the script.
	// This is the cheap guard that catches a reintroduced upstream literal.
	s.check(
		!releaseScriptSource.includes(UPSTREAM),
		"build-server-release.mjs has no upstream URL left in it",
	);
	s.check(
		releaseScriptSource.includes(FORK),
		"build-server-release.mjs builds fork URLs",
	);
}

void s.done();
